# Generated by Django 2.2.3 on 2022-08-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Anônimo', max_length=20)),
                ('mensagem', models.CharField(max_length=200)),
            ],
        ),
    ]
