# Generated by Django 2.2.3 on 2022-08-20 22:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Anônimo', max_length=20)),
                ('mensagem', models.TextField(max_length=200)),
                ('mostrar', models.BooleanField(default=True)),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('gostei', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Marcelo', max_length=15)),
                ('resposta', models.TextField()),
                ('cometario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Mensagem')),
            ],
        ),
    ]
