# Generated by Django 2.2.3 on 2022-08-20 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Anônimo', max_length=20)),
                ('mensagem', models.CharField(max_length=200)),
                ('mostrar', models.BooleanField(default=True)),
                ('data', models.DateTimeField(default=datetime.datetime)),
            ],
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
