# Generated by Django 2.2.3 on 2022-08-20 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20220820_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 1, 15, 0, 691156)),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='mensagem',
            field=models.TextField(max_length=200),
        ),
    ]
