# Generated by Django 2.2.3 on 2022-08-20 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20220820_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='gostei',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
